---

- name: install an Ubuntu desktop
  apt: name="ubuntu-desktop" install-recommends=yes state=present
   
#- name: set compiz workspaces to 1line
#  command: >
#            gsettings set
#            org.compiz.core:/org/compiz/profiles/unity/plugins/core/ vsize 1
#            &&
#            gsettings set
#            org.compiz.core:/org/compiz/profiles/unity/plugins/core/ hsize 4

- name: install packages
  apt: name="{{item}}" state=present
  with_items:
    - chromium-browser
    - curl
    # ...

- include: mono.yml
