---

- name: install packages
  apt: name="{{item}}" state=present
  with_items:
    - vim
    - curl
    # ...
    
- name: install a minimal Ubuntu desktop before Pantheon
  apt: name="ubuntu-desktop" install-recommends=no state=present

- include: mono.yml
- include: pantheon.yml
